version: "3.5"
services:
  vue-account:
    image: hatlonely/vue-account:v1.1.0
    hostname: vue-account
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - vue-accountnet
networks:
  vue-accountnet:
    name: vue-accountnet
