version: "3.5"
services:
  nginx:
    image: hatlonely/vue-account:v1.0.0
    hostname: vue-account
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6000:80"
    volumes:
      - "${HOME}/var/docker/vue-account/log:/var/log/nginx"
      - "${HOME}/var/docker/vue-account/run:/var/run"
    networks:
      - vueaccountnet
networks:
  vueaccountnet:
    name: vueaccountnet
